version: "3"
services:
  api:
      build: .
      depends_on:
          - postgres
      volumes:
          - ./:/usr/src/app:ro
      command: uvicorn app.main:app --host localhost --port 8000 --reload
      ports:
          - "8000:8000"
      environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
      image: postgres
      environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_HOST=${DATABASE_HOSTNAME}
      - POSTGRES_DB=${DATABASE_NAME}
      ports:
          - "5432:5432"
      volumes:
          - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: